#!/bin/sh
set -e
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"
lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --debootstrap-options "--variant=minbase --include=ca-certificates" \
  --apt-recommends false \
  --firmware-chroot false \
  --debian-installer none \
  --win32-loader false \
  --memtest none \
  --bootappend-live "boot=live components quiet splash noeject hostname=sventos username=user" \
  --iso-application "SventOS" \
  --iso-volume "SventOS Live" \
  --iso-publisher "z1rov" \
  "${@}"
