#!/bin/sh
set -e
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:${PATH:-}"
lb config noauto \
  --distribution trixie \
  --distribution-chroot trixie \
  --distribution-binary trixie \
  --binary-image iso-hybrid \
  --bootloaders "syslinux grub-efi" \
  --chroot-squashfs-compression-type xz \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --debootstrap-options "--variant=minbase --include=ca-certificates" \
  --apt-recommends false \
  --firmware-chroot true \
  --debian-installer none \
  --win32-loader false \
  --memtest none \
  --bootappend-live "boot=live components quiet noeject hostname=sventos username=svent-live locales=en_US.UTF-8 live-config.user-default-groups=audio,cdrom,dip,floppy,video,plugdev,netdev,powerdev,scanner,bluetooth,sudo" \
  --iso-application "SventOS" \
  --iso-volume "SventOS Live" \
  --iso-publisher "z1rov" \
  "${@}"
