---
efiBootLoader: "grub"
kernelSearchPath: "/boot"
kernel: "/vmlinuz"
img: "/initrd.img"
timeout: "5"
bootloaderEntryName: "SventOS"
installEFIFallback: true
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
grubCfg: "/boot/grub/grub.cfg"
efiBootloaderId: "SventOS"
