---
backend: apt
skip_if_no_internet: false
update_db: false
update_system: false
operations:
  - remove:
    - calamares
    - live-boot
    - live-boot-initramfs-tools
    - live-config
    - live-config-systemd
