---
efi:
    mountPoint: /boot/efi
    recommendedSize: 512MiB
    minimumSize: 300MiB
    label: EFI
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: file
defaultFileSystemType: "ext4"
