---
efiSystemPartition: "/boot/efi"
userSwapChoices:
    - none
    - small
    - suspend
    - file
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialSwapChoice: file
defaultFileSystemType: "ext4"
