---
units:
    - name: NetworkManager.service
      action: enable
      mandatory: true
    - name: lxdm.service
      action: enable
      mandatory: true
    - name: cups.service
      action: enable
      mandatory: true
    - name: avahi-daemon.service
      action: enable
      mandatory: true
    - name: apparmor.service
      action: enable
      mandatory: true
