---
dontChroot: false
timeout: 180
script:
    - "systemctl set-default graphical.target"
    - "systemctl enable lxdm.service || true"
    - "rm -f /etc/systemd/system/getty@tty1.service.d/override.conf"
    - "rmdir /etc/systemd/system/getty@tty1.service.d 2>/dev/null || true"
    - "rm -f /root/.bash_profile /root/.xinitrc"
    - "rm -f /etc/xdg/openbox/autostart"
    - "apt-get autoremove --purge -y || true"
    - "apt-get clean"
