---
defaultGroups:
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - bluetooth
autologinGroup: ""
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
doReusePassword: false
user:
    shell: /bin/bash
    forbidden_names: [root, nobody, svent-live]
    home_permissions: "o700"
