---
modules-search: [ local, /usr/lib/x86_64-linux-gnu/calamares/modules ]
instances:
- id: finalize
  module: shellprocess
  config: shellprocess-finalize.conf
sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - removeuser
  - bootloader
  - grubcfg
  - shellprocess@finalize
  - umount
- show:
  - finished
branding: svent
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
